<?php
include ("/m23/inc/packages.php");
include ("/m23/inc/checks.php");
include ("/m23/inc/client.php");
include ("/m23/inc/capture.php");

$params = PKG_OptionPageHeader2("gitalist-common");

$elem["gitalist/directory"]["type"]="string";
$elem["gitalist/directory"]["description"]="Path to Git repositories:
 Please specify the path from which Gitalist should serve Git repositories.
 .
 These should be \"bare\" repositories.
";
$elem["gitalist/directory"]["descriptionde"]="Pfad zu den Git-Depots:
 Bitte geben Sie das Verzeichnis an, aus dem Gitalist Git-Depots bereitstellen soll.
 .
 Dies sollten »bare« Depots sein.
";
$elem["gitalist/directory"]["descriptionfr"]="Répertoire contenant les dépôts Git :
 Veuillez indiquer le répertoire à partir duquel Gitalist servira les dépôts Git.
 .
 Ces dépôts doivent être des dépôts « nus » (bare).
";
$elem["gitalist/directory"]["default"]="/srv/git";
$elem["gitalist/gravatar"]["type"]="boolean";
$elem["gitalist/gravatar"]["description"]="Enable Gravatar support?
 Gravatar is a web service associating user email addresses with \"avatars\".
 It is independent of the Gitalist upstream authors. The pages generated by
 Gitalist can show these \"avatars\" for users who have registered with Gravatar.
 .
 Gravatar support in Gitalist is disabled by default because it can leak
 information about repositories, directories, and files via browser referrals
 to the Gravatar service.
";
$elem["gitalist/gravatar"]["descriptionde"]="Gravatar-Unterstützung aktivieren?
 Gravatar ist ein Web-Dienst, der E-Mail-Adressen von Benutzern »Avataren« zuordnet. Er ist unabhängig von den Gitalist-Ursprungsautoren. Die von Gitalist generierten Seiten können diese »Avatare« für Benutzer anzeigen, die bei Gravatar registriert sind.
 .
 Gravatar-Unterstützung ist in Gitalist standardmäßig deaktiviert, da Informationen über Depots, Verzeichnisse und Dateien über HTTP-Referrer an den Gravatar-Dienst durchsickern können.
";
$elem["gitalist/gravatar"]["descriptionfr"]="Activer la prise en charge de Gravatar ?
 Gravatar est un service web associant les adresses électroniques des utilisateurs avec leur « avatar ». Cette fonctionnalité est indépendante des auteurs amont de Gitalist. Les pages générées par Gitalist peuvent afficher ces « avatars » pour les utilisateurs qui sont enregistrés auprès de Gravatar.
 .
 La prise en charge de Gravatar dans Gitalist est désactivée par défaut car cela peut révéler des informations à propos des dépôts, répertoires et fichiers à l'aide de référants du navigateur vers le service Gravatar.
";
$elem["gitalist/gravatar"]["default"]="false";
$elem["gitalist/whitelist"]["type"]="select";
$elem["gitalist/whitelist"]["choices"][1]="none";
$elem["gitalist/whitelist"]["choices"][2]="gitolite";
$elem["gitalist/whitelist"]["description"]="File that contains a whitelist of repositories to be displayed:
 If you use an SSH gatekeeper to maintain your git repositories on the
 server, such as Gitolite, you can specify the whitelist file
 that defines what repositories get presented in the webfrontend.
 .
 The default whitelist for Gitolite is the projects.list file
 in the parent directory of the directory where the git repositories are
 stored.
";
$elem["gitalist/whitelist"]["descriptionde"]="";
$elem["gitalist/whitelist"]["descriptionfr"]="Fichier contenant une liste blanche de dépôts à afficher :
 Si un portier SSH (« SSH gatekeeper ») est utilisé pour maintenir des dépôts Git sur le serveur, comme Gitolite, vous pouvez indiquer le fichier de liste blanche qui définit les dépôts qui seront présents sur l'interface web.
 .
 La liste blanche par défaut pour Gitolite est le fichier « projects.list » dans le dossier parent du dossier où le dépôt Git est enregistré.
";
$elem["gitalist/whitelist"]["default"]="none";
$elem["gitalist/whitelist_custom"]["type"]="string";
$elem["gitalist/whitelist_custom"]["description"]="Path to file that contains a whitelist of repositories:
 Please specify the path to the whiteliste file. This file contains an list
 of repositories that will be served by Gitalist.
";
$elem["gitalist/whitelist_custom"]["descriptionde"]="";
$elem["gitalist/whitelist_custom"]["descriptionfr"]="Chemin du fichier contenant une liste blanche de dépôts :
 Veuillez indiquer le fichier de liste blanche. Ce fichier contient une liste de dépôts qui seront servis par Gitalist.
";
$elem["gitalist/whitelist_custom"]["default"]="";
PKG_OptionPageTail2($elem);
?>
