<u>Vorgemerkte Pakete im-/exportieren</u><!-- v13.2 new-->
Die in der Liste unter "<i>$I18N_preselected_packages</i>" stehenden Paketnamen können Sie mit einem Klick auf "<i>$I18N_exportSelectedPackages</i>" in einer Datei speichern. Zum Importieren klicken Sie auf "<i>Durchsuchen ...</i>" (bzw. auf den in Ihrem Browser ggf. anders beschrifteten Button zur Dateiauswahl) und wählen die Datei mit den vorgemerkten Paketnamen aus. Klicken Sie anschließend auf "<i>$I18N_upload</i>".

<u>Hinweis</u>
In den exportierten Dateien sind die Paketnamen durch Leerzeichen getrennt aufgelistet.