<!-- v1.5--><u>Hinweis zu Paketzusammenstellungen</u>
Wenn Sie "Paketzusammenstellung" auswählen, können Sie bestimmen, ob die Pakete auf dem Client installiert oder deinstalliert werden sollen. Außerdem können Sie die in der Paketzusammenstellung gespeicherte Aktionen beibehalten. Dies erlaubt es, Installations- und Deinstallations-Aufträge in einer einzigen Zusammenstellung zu benutzen. Wählen Sie dazu aus der Auswahlliste die gewünschte Aktion aus.<!--end v1.5-->

<u>Tip</u>
Möchten Sie Ihre Paketauswahl für spätere Benutzung sichern, geben Sie nach <i>"$I18N_save_package_selection"</i> einen Namen für Ihre Zusammenstellung ein und sichern Sie diese mit dem <i>"$I18N_save"</i>-Button. Diese Zusammenstellung steht Ihnen sofort unter <i>"$I18N_package_selection"</i> zur Verfügung.
