<u>Hinweis</u>
m23 unterscheidet drei verschiedene Paketarten:
<ul><LI><b>$I18N_package_selection:</b> Sind eine Zusammenstellung von verschiedenen Paketen. Sie können aus einer Vielzahl von Anwendungen ein Paket schnüren und so die Installation von identischen Programmpaketen auf verschiedenen Rechnern enorm erleichtern.</LI>
<li><b>$I18N_normal_packages:</b> Sind normale Programmpakete. Dies sind in der Regel einzelne Programme.</li>
<li><b>$I18N_special_packages:</b> Enthalten Pakete, die Spezialaufgaben wie Formatieren etc. durchführen. Spezialpakete sollten nur durch erfahrene Benutzer angewendet werden.</li></ul>
