<!-- v16.3--><u>$I18N_poolGPGSignKey</u>
Hier können Sie den privaten GPG-Schlüssel auswählen, der zum Signieren der auf Ihrem m23-Server erstellten Paketquellen verwendet wird. Auf die m23-Clients wird der dazugehörige öffentliche Schlüssel übertragen, damit diese die Unverfälschtheit der Pakete überprüfen können.

Unter <i>"$I18N_currentlyUsedGPGKey"</i> sehen Sie den aktuell verwendeten Schlüssel. Sollte hier kein Schlüssel angegeben sein, so werden die Pakete auf Ihrem m23-Server aktuell nicht signiert.

Zum Nutzen eines privaten GPG-Schlüssels wählen Sie diesen aus der Liste aus und klicken Sie anschließend auf <i>"$I18N_select"</i>. Der GPG-Schlüssel wird nun zum Signieren aller neu erstellten oder aktualisierten Paketquellen verwendet und auch auf neu angelegte oder wiederhergestellte m23-Clients übertragen.

Möchten Sie vorhandene GPG-Schlüssel entfernen oder neue hinzufügen, so klicken Sie auf <i>"$I18N_manageGPGKeys"</i>.