<?php
include ("/m23/inc/packages.php");
include ("/m23/inc/checks.php");
include ("/m23/inc/client.php");
include ("/m23/inc/capture.php");

$params = PKG_OptionPageHeader2("libpaper1");

$elem["libpaper/defaultpaper"]["type"]="select";
$elem["libpaper/defaultpaper"]["choices"][1]="letter";
$elem["libpaper/defaultpaper"]["choices"][2]="a4";
$elem["libpaper/defaultpaper"]["choices"][3]="note";
$elem["libpaper/defaultpaper"]["choices"][4]="legal";
$elem["libpaper/defaultpaper"]["choices"][5]="executive";
$elem["libpaper/defaultpaper"]["choices"][6]="halfletter";
$elem["libpaper/defaultpaper"]["choices"][7]="halfexecutive";
$elem["libpaper/defaultpaper"]["choices"][8]="11x17";
$elem["libpaper/defaultpaper"]["choices"][9]="statement";
$elem["libpaper/defaultpaper"]["choices"][10]="folio";
$elem["libpaper/defaultpaper"]["choices"][11]="quarto";
$elem["libpaper/defaultpaper"]["choices"][12]="10x14";
$elem["libpaper/defaultpaper"]["choices"][13]="ledger";
$elem["libpaper/defaultpaper"]["choices"][14]="tabloid";
$elem["libpaper/defaultpaper"]["choices"][15]="a0";
$elem["libpaper/defaultpaper"]["choices"][16]="a1";
$elem["libpaper/defaultpaper"]["choices"][17]="a2";
$elem["libpaper/defaultpaper"]["choices"][18]="a3";
$elem["libpaper/defaultpaper"]["choices"][19]="a5";
$elem["libpaper/defaultpaper"]["choices"][20]="a6";
$elem["libpaper/defaultpaper"]["choices"][21]="a7";
$elem["libpaper/defaultpaper"]["choices"][22]="a8";
$elem["libpaper/defaultpaper"]["choices"][23]="a9";
$elem["libpaper/defaultpaper"]["choices"][24]="a10";
$elem["libpaper/defaultpaper"]["choices"][25]="b0";
$elem["libpaper/defaultpaper"]["choices"][26]="b1";
$elem["libpaper/defaultpaper"]["choices"][27]="b2";
$elem["libpaper/defaultpaper"]["choices"][28]="b3";
$elem["libpaper/defaultpaper"]["choices"][29]="b4";
$elem["libpaper/defaultpaper"]["choices"][30]="b5";
$elem["libpaper/defaultpaper"]["choices"][31]="c5";
$elem["libpaper/defaultpaper"]["choices"][32]="DL";
$elem["libpaper/defaultpaper"]["choices"][33]="Comm10";
$elem["libpaper/defaultpaper"]["choices"][34]="Monarch";
$elem["libpaper/defaultpaper"]["choices"][35]="archE";
$elem["libpaper/defaultpaper"]["choices"][36]="archD";
$elem["libpaper/defaultpaper"]["choices"][37]="archC";
$elem["libpaper/defaultpaper"]["choices"][38]="archB";
$elem["libpaper/defaultpaper"]["choices"][39]="archA";
$elem["libpaper/defaultpaper"]["choices"][40]="flsa";
$elem["libpaper/defaultpaper"]["choices"][41]="flse";
$elem["libpaper/defaultpaper"]["choices"][42]="csheet";
$elem["libpaper/defaultpaper"]["choices"][43]="dsheet";
$elem["libpaper/defaultpaper"]["choicesde"][1]="letter";
$elem["libpaper/defaultpaper"]["choicesde"][2]="A4";
$elem["libpaper/defaultpaper"]["choicesde"][3]="note";
$elem["libpaper/defaultpaper"]["choicesde"][4]="legal";
$elem["libpaper/defaultpaper"]["choicesde"][5]="executive";
$elem["libpaper/defaultpaper"]["choicesde"][6]="halfletter";
$elem["libpaper/defaultpaper"]["choicesde"][7]="halfexecutive";
$elem["libpaper/defaultpaper"]["choicesde"][8]="11x17";
$elem["libpaper/defaultpaper"]["choicesde"][9]="statement";
$elem["libpaper/defaultpaper"]["choicesde"][10]="folio";
$elem["libpaper/defaultpaper"]["choicesde"][11]="quarto";
$elem["libpaper/defaultpaper"]["choicesde"][12]="10x14";
$elem["libpaper/defaultpaper"]["choicesde"][13]="ledger";
$elem["libpaper/defaultpaper"]["choicesde"][14]="tabloid";
$elem["libpaper/defaultpaper"]["choicesde"][15]="A0";
$elem["libpaper/defaultpaper"]["choicesde"][16]="A1";
$elem["libpaper/defaultpaper"]["choicesde"][17]="A2";
$elem["libpaper/defaultpaper"]["choicesde"][18]="A3";
$elem["libpaper/defaultpaper"]["choicesde"][19]="A5";
$elem["libpaper/defaultpaper"]["choicesde"][20]="A6";
$elem["libpaper/defaultpaper"]["choicesde"][21]="A7";
$elem["libpaper/defaultpaper"]["choicesde"][22]="A8";
$elem["libpaper/defaultpaper"]["choicesde"][23]="A9";
$elem["libpaper/defaultpaper"]["choicesde"][24]="A10";
$elem["libpaper/defaultpaper"]["choicesde"][25]="B0";
$elem["libpaper/defaultpaper"]["choicesde"][26]="B1";
$elem["libpaper/defaultpaper"]["choicesde"][27]="B2";
$elem["libpaper/defaultpaper"]["choicesde"][28]="B3";
$elem["libpaper/defaultpaper"]["choicesde"][29]="B4";
$elem["libpaper/defaultpaper"]["choicesde"][30]="B5";
$elem["libpaper/defaultpaper"]["choicesde"][31]="C5";
$elem["libpaper/defaultpaper"]["choicesde"][32]="DL";
$elem["libpaper/defaultpaper"]["choicesde"][33]="Comm10";
$elem["libpaper/defaultpaper"]["choicesde"][34]="Monarch";
$elem["libpaper/defaultpaper"]["choicesde"][35]="archE";
$elem["libpaper/defaultpaper"]["choicesde"][36]="archD";
$elem["libpaper/defaultpaper"]["choicesde"][37]="archC";
$elem["libpaper/defaultpaper"]["choicesde"][38]="archB";
$elem["libpaper/defaultpaper"]["choicesde"][39]="archA";
$elem["libpaper/defaultpaper"]["choicesde"][40]="flsa";
$elem["libpaper/defaultpaper"]["choicesde"][41]="flse";
$elem["libpaper/defaultpaper"]["choicesde"][42]="csheet";
$elem["libpaper/defaultpaper"]["choicesde"][43]="dsheet";
$elem["libpaper/defaultpaper"]["choicesfr"][1]="Lettre US";
$elem["libpaper/defaultpaper"]["choicesfr"][2]="A4";
$elem["libpaper/defaultpaper"]["choicesfr"][3]="Note";
$elem["libpaper/defaultpaper"]["choicesfr"][4]="Légal";
$elem["libpaper/defaultpaper"]["choicesfr"][5]="Exécutive";
$elem["libpaper/defaultpaper"]["choicesfr"][6]="Demi-lettre";
$elem["libpaper/defaultpaper"]["choicesfr"][7]="Demi-exécutive";
$elem["libpaper/defaultpaper"]["choicesfr"][8]="11x17";
$elem["libpaper/defaultpaper"]["choicesfr"][9]="Statement";
$elem["libpaper/defaultpaper"]["choicesfr"][10]="Folio";
$elem["libpaper/defaultpaper"]["choicesfr"][11]="Quarto";
$elem["libpaper/defaultpaper"]["choicesfr"][12]="10x14";
$elem["libpaper/defaultpaper"]["choicesfr"][13]="Ledger";
$elem["libpaper/defaultpaper"]["choicesfr"][14]="Tabloïd";
$elem["libpaper/defaultpaper"]["choicesfr"][15]="A0";
$elem["libpaper/defaultpaper"]["choicesfr"][16]="A1";
$elem["libpaper/defaultpaper"]["choicesfr"][17]="A2";
$elem["libpaper/defaultpaper"]["choicesfr"][18]="A3";
$elem["libpaper/defaultpaper"]["choicesfr"][19]="A5";
$elem["libpaper/defaultpaper"]["choicesfr"][20]="A6";
$elem["libpaper/defaultpaper"]["choicesfr"][21]="A7";
$elem["libpaper/defaultpaper"]["choicesfr"][22]="A8";
$elem["libpaper/defaultpaper"]["choicesfr"][23]="A9";
$elem["libpaper/defaultpaper"]["choicesfr"][24]="A10";
$elem["libpaper/defaultpaper"]["choicesfr"][25]="B0";
$elem["libpaper/defaultpaper"]["choicesfr"][26]="B1";
$elem["libpaper/defaultpaper"]["choicesfr"][27]="B2";
$elem["libpaper/defaultpaper"]["choicesfr"][28]="B3";
$elem["libpaper/defaultpaper"]["choicesfr"][29]="B4";
$elem["libpaper/defaultpaper"]["choicesfr"][30]="B5";
$elem["libpaper/defaultpaper"]["choicesfr"][31]="C5";
$elem["libpaper/defaultpaper"]["choicesfr"][32]="DL";
$elem["libpaper/defaultpaper"]["choicesfr"][33]="Comm10";
$elem["libpaper/defaultpaper"]["choicesfr"][34]="Monarch";
$elem["libpaper/defaultpaper"]["choicesfr"][35]="ArchE";
$elem["libpaper/defaultpaper"]["choicesfr"][36]="ArchD";
$elem["libpaper/defaultpaper"]["choicesfr"][37]="ArchC";
$elem["libpaper/defaultpaper"]["choicesfr"][38]="ArchB";
$elem["libpaper/defaultpaper"]["choicesfr"][39]="ArchA";
$elem["libpaper/defaultpaper"]["choicesfr"][40]="FLSA";
$elem["libpaper/defaultpaper"]["choicesfr"][41]="FLSE";
$elem["libpaper/defaultpaper"]["choicesfr"][42]="Csheet";
$elem["libpaper/defaultpaper"]["choicesfr"][43]="Dsheet";
$elem["libpaper/defaultpaper"]["description"]="System's default paper size:
 Please select the default paper size for the system.
 Various programs on the system will use this configuration option to
 determine how to print output.
";
$elem["libpaper/defaultpaper"]["descriptionde"]="Standard-Papierformat für Ihr System:
 Bitte wählen Sie das Standard-Papierformat für Ihr System. Verschiedene Programme werden diese Vorgabe verwenden, um zu bestimmen, in welchem Format etwas gedruckt werden soll. Normalerweise ist »A4« das richtige Format.
";
$elem["libpaper/defaultpaper"]["descriptionfr"]="Format de papier par défaut pour le système :
 Veuillez choisir le format de papier par défaut pour le système. De nombreux programmes l'utiliseront pour configurer leur mode d'impression.
";
$elem["libpaper/defaultpaper"]["default"]="";
PKG_OptionPageTail2($elem);
?>
