<u>Im/Export selected packages</u><!-- v13.2 new-->
A click on "<i>$I18N_exportSelectedPackages</i>" stores the packages listed under "<i>$I18N_preselected_packages</i>" to a file. For the import of packages click on "<i>Browse ...</i>" (and otherwise labeled in your browser respectively) and choose the file with the preselected packages. Then click on "<i>$I18N_upload</i>".

<u>Hint</u>
The package names are seperated by blanks in the exported files.