<!-- v1.5--><u>Hint for package selections</u>
If you select a package selection, you can choose the action for the packages. You have the possibility to install or deinstall the packages on or from the client. Or you can keep the stored action. This makes it possible to store installation and deinstallation jobs in the same package selection. Simply select the desired action from the selection list.<!--end v1.5-->

<u>Hint</u>
If you want to save your package selection, enter a name for the selection at <i>"$I18N_save_package_selection"</i> and click the <i>"$I18N_save"</i> button. Afterwards, you can use your selection as a <i>"$I18N_package_selection"</i>.
