<u>Hint</u>
m23 differentiates between three kinds of packages:<ul>
<LI><b>$I18N_package_selection:</b> Are a selection of different software packages. You can make selections like <i>"office selection"</i> or <i>"graphic workstation selection"</i>. So you don't have to select each single software package but you can use the package selection.
<LI><b>$I18N_normal_packages:</b> Are the normal software packages. They are mostly single applications.</LI>
<LI><b>$I18N_special_packages:</b> Are packages for special tasks like formatting, setting of network options etc. Special packages should only be used by skilful users.</LI></ul>
