<!-- v16.3--><u>$I18N_poolGPGSignKey</u>
Select the private GPG key that will be used to sign the package sources created with your m23 server here. The corresponding public key will be transferred to the m23 clients, so the authenticity of the packages can be checked.

At <i>"$I18N_currentlyUsedGPGKey"</i>, the key which is currently in use is displayed. If there is no key indicated, the packages will currently not be signed.

To be able to use a private GPG key, select one from the list and click on <i>"$I18N_select"</i>. The GPG key will now be used to sign all package sources that are created or updated, and will also be transferred to clients that are created or restored.

If you would like to remove or add a GPG key, click on <i>"$I18N_manageGPGKeys"</i>.
