<u>Im-/Exporter des paquets présélectionnés</u><!-- v13.2 new-->
Les noms des paquets de la liste "<i>$I18N_preselected_packages</i>" peuvent être sauvegardé dans un fichier par un clic de souris sur "<i>$I18N_exportSelectedPackages</i>". Pour l'import, cliquez sur "<i>Chercher ...</i>" (ou le bouton pour le choix d'un fichier qui porte un texte différent dans votre navigateur web) et sélectionnez le fichier avec les noms des paquets présélectionnés. Enfin, cliquez sur "<i>$I18N_upload</i>".

<u>Notez</u>
Dans les fichiers d'exportation, les noms des paquets sont séparés par des espaces.