<!-- v1.5--><u>Notez: Combinaisons de paquets</u>
Si vous cliquez sur <i>&laquo;Combinaisons de paquets&raquo;</i>, vous pouvez décider l'installation ou la désinstallation des paquets sur le poste client. De plus, vous pouvez conserver les actions enregistrées dans la combinaison de paquets. Ceci vous permet d'utiliser des travaux d'installation et de désinstallation dans une combinaison particulière. Pour cela, choisissez l'action souhaitée dans la liste.<!--end v1.5-->

<u>CONSEIL:</u>
Si vous souhaitez enregistrer votre choix de paquets afin de pouvoir l'utiliser plus tard, entrez un nom pour votre combinaison de paquets après <i>&laquo;$I18N_save_package_selection&raquo;</i>, puis cliquez sur <i>&laquo;$I18N_save&raquo;</i>. Cette combinaison sera à votre disposition dès validation dans les <i>&laquo;$I18N_package_selection&raquo;</i>.
