<u>Notez</u>
m23 distingue trois types de paquet différents:<ul>
<LI><b>$I18N_package_selection:</b> Ce sont des combinaisons de paquets distincts appelés également meta-paquets. Vous pouvez regrouper un nombre conséquent d'applications dans un meta-paquet et ainsi simplifier énormément l'installation des paquets identiques sur plusieurs ordinateurs.</LI>
<LI><b>$I18N_normal_packages:</b> Ce sont des paquets de programmes standards. Il s'agit, en général, des programmes isolés.</LI>
<LI><b>$I18N_special_packages:</b> Ils contiennent des paquets devant exécuter des travaux spéciaux comme formater etc., qui devraient être utilisés seulement par des utilisateurs expérimentés.</LI></ul>
