<!-- v16.3--><u>$I18N_poolGPGSignKey</u>
Selectionnez la clé GPG privée à utiliser pour la signature des paquets sources devant êtres créés par votre serveur m23. La clé publique correspondante sera transférée sur les clients m23, ceci permettra de valider l'authenticité des paquets provenant de votre serveur m23.

Lorsque <i>"$I18N_currentlyUsedGPGKey"</i>, la clé en cours d'utilisation est affichée. Si aucune clé n'apparait, les paquets ne seront pas signés.

Afin de pouvoir utiliser une clé GPG privée, sélectionnez en une dans la liste puis cliquez sur <i>"$I18N_select"</i>. La clé GPG sera dès aprésent utilisée pour signer tous les paquets sources créés ou modifiés; ces paquets seront par la même occasion transférés sur les clients.

Si vous désirez supprimer ou ajouter une clé GPG, cliquez sur <i>"$I18N_manageGPGKeys"</i>.
